In [2]:
#IMPORTING THE PANDAS 

import pandas as pd

In [7]:
#IMPORTING THE DATASET CSV FILE.

df = pd.read_csv(r"smartphones.csv")

In [8]:
#GETTING A CONCISE SUMMARY OF THE DATAFRAME. 
#USING .info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [9]:
#GETTING THE STATISTICAL SUMMARY OF THE DATAFRAME.
#USING .describe()

df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [10]:
#TO RETURN THE FIRST 'n' ROWS OF A DATAFRAME (DEFAULT 5 ROWS)


df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [20]:
#TO RETURN THE LAST 'n' ROWS OF A DATAFRAME (DEFAULT 5 ROWS)


df.tail()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
1015,Motorola Moto Edge S30 Pro,"₹34,990",83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,"₹14,990",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),"₹28,990",85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,"₹19,990",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,"₹24,990",74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [22]:
#CHECKING THE NUMBER OF ROWS AND COLOUMNS


df.shape

(1020, 11)

In [ ]:
#CHECKING WHERE VALUES ARE MISSING (TRUE/FALSE)


df.isnull()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,False,False,False
1017,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,False,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#COUNTING MISSING VALUES PER COLOUMN


df.isnull().sum()

model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [ ]:
#TOTAL MISSING VALUES IN THE DATASET


df.isnull().sum().sum()

np.int64(166)

In [ ]:
#CHECK DATA TYPES


df.dtypes

model         object
price         object
rating       float64
sim           object
processor     object
ram           object
battery       object
display       object
camera        object
card          object
os            object
dtype: object

In [24]:
#FILLING MISSING RATINGS WITH MEAN


df['rating'] = df['rating'].fillna(df['rating'].mean())

In [25]:
#FILLING MISSING CATEGORICAL COLOUMNS WITH MODE


for col in ['camera', 'card', 'os']:
    df[col] = df[col].fillna(df[col].mode()[0])

In [26]:
#VERIFYING


print("\nMissing values after handling:\n", df.isnull().sum())

Missing values after handling:
 model        0
price        0
rating       0
sim          0
processor    0
ram          0
battery      0
display      0
camera       0
card         0
os           0
dtype: int64

In [27]:
#CHECKING NUMBER OF DUPLICATE ROWS


print("Duplicate rows before:", df.duplicated().sum())

Duplicate rows before: 0

In [28]:
#REMOVING DUPLICATES


df.drop_duplicates(inplace=True)

In [29]:
#CHECKING AGAIN


print("Duplicate rows after:", df.duplicated().sum())

Duplicate rows after: 0

In [ ]:
#CLEAN AND CONVERT NUMERIC COLOUMNS STORED AS TEXT

In [30]:
#REMOVING ₹ AND COMMAS , CONVERTING PRICE TO FLOAT


df['price'] = df['price'].replace('[₹,]', '', regex=True).astype(float)

In [33]:
#EXTRACTING NUMERIC RAM IN GB


df['ram'] = df['ram'].astype(str).str.extract(r'(\d+)').astype(float)

In [35]:
#EXTRACTING BATTERY CAPACITY IN MAH


df['battery'] = df['battery'].astype(str).str.extract(r'(\d+)').astype(float)

In [36]:
#EXTRACTING DISPLAY SIZE IN INCHES


df['display'] = df['display'].astype(str).str.extract(r'(\d+\.\d+)').astype(float)

In [37]:
#EXTRACTING MAIN CAMERA MEGAPIXELS


df['camera'] = df['camera'].astype(str).str.extract(r'(\d+)').astype(float)

In [40]:
#VERIFYING DATATYPES


df.dtypes

model         object
price        float64
rating       float64
sim           object
processor     object
ram          float64
battery      float64
display      float64
camera       float64
card          object
os            object
dtype: object

In [ ]:
#ENSURING THE DATASET IS CLEAN AND READY FOR ANALYSIS

In [41]:
#STANDARDISE COLOUMN NAMES


df.columns = df.columns.str.strip().str.lower()

In [42]:
#FINAL VALIDATION


print("Shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nData types:\n", df.dtypes)
print("\nPreview cleaned data:\n", df.head())

Shape: (1020, 11)

Missing values:
 model         0
price         0
rating        0
sim           0
processor     0
ram           1
battery       1
display      49
camera       48
card          0
os            0
dtype: int64

Data types:
 model         object
price        float64
rating       float64
sim           object
processor     object
ram          float64
battery      float64
display      float64
camera       float64
card          object
os            object
dtype: object

Preview cleaned data:
                        model    price  rating  \
0              OnePlus 11 5G  54999.0    89.0
1  OnePlus Nord CE 2 Lite 5G  19989.0    81.0
2      Samsung Galaxy A14 5G  16499.0    75.0
3       Motorola Moto G62 5G  14999.0    81.0
4         Realme 10 Pro Plus  24999.0    82.0

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi

                                         processor   ram  battery  display  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12.0   5000.0     6.70
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6.0   5000.0     6.59
2        Exynos 1330, Octa Core, 2.4 GHz Processor   4.0   5000.0     6.60
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6.0   5000.0     6.55
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6.0   5000.0     6.70

   camera                              card           os
0    50.0         Memory Card Not Supported  Android v13
1    64.0   Memory Card (Hybrid), upto 1 TB  Android v12
2    50.0  Memory Card Supported, upto 1 TB  Android v13
3    50.0   Memory Card (Hybrid), upto 1 TB  Android v12
4   108.0         Memory Card Not Supported  Android v13

In [43]:
#DATA SET IS READY FOR ANALYSIS

#FOR SAVING THE CLEANED DATA SET   ===>
                         #OPTIONAL


df.to_csv("smartphones_cleaned.csv", index=False)